import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",

    // Generated / vendored / non-source trees. These are already in .gitignore,
    // but flat config does NOT read .gitignore (the eslintrc era did), so every
    // one of them has to be listed here too. Without these the repo-wide
    // `npm run lint` reported 1654 errors, 1561 of which came from files nobody
    // authors by hand:
    //   src/generated/prisma  — Prisma client, 913 errors, regenerated by `prisma generate`
    //   .releases             — deploy.sh source snapshots, 621 errors
    //   ws-server/dist        — compiled output, 27 errors
    "src/generated/**",
    ".releases/**",
    "ws-server/dist/**",

    // Same story for anything else .gitignore already excludes as build output.
    "ws-server/.next/**",
    "docs/promo/.next/**",
  ]),
]);

export default eslintConfig;
